# Generated by Django 4.2.16 on 2024-11-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Standings',
        ),
    ]
