# Generated by Django 4.2.16 on 2024-11-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_playerprofile_draws_playerprofile_losses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
