# Generated by Django 4.2.16 on 2024-11-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_playerprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='slack_url',
            field=models.URLField(blank=True),
        ),
    ]
