# Generated by Django 4.2.16 on 2024-11-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_playerprofile_slack_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='slack_avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
