# Generated by Django 4.2.16 on 2024-11-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_playerprofile_slack_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='slack_avatar',
        ),
    ]
